// let store: MockStore<{ FormElements: [] }>;
//   const initialState = { FormElements: [
//     {
//       id: '1111',
//       type: 'input',
//       placeholderText: 'Input placeholder',
//       width: 100,
//       height: 50,
//       required: false,
//       borderWidth: '1',
//       borderColor: '#cccccc',
//       borderStyle: 'solid', 
//       fontSize: 14,
//       fontWeight: 400,
//       color: '#000000',
//     },
//     {
//       id: '2222',
//       type: 'textarea',
//       placeholderText: 'Text placeholder',
//       width: 100,
//       height: 100,
//       required: false,
//       borderWidth: '1',
//       borderColor: '#cccccc',
//       borderStyle: 'solid', 
//       fontSize: 14,
//       fontWeight: 400,
//       color: '#000000',
//     },
//     {
//       id: '3333',
//       type: 'input',
//       placeholderText: 'Input placeholder',
//       width: 100,
//       height: 50,
//       required: false,
//       borderWidth: '1',
//       borderColor: '#cccccc',
//       borderStyle: 'solid', 
//       fontSize: 14,
//       fontWeight: 400,
//       color: '#000000',
//     },
//   ] };